basePath: /
definitions:
  controllers.LoginInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controllers.RegisterInput:
    properties:
      email:
        description: 必填，且必須符合 Email 格式!
        type: string
      password:
        description: 必填，且密碼至少要 6 個字!
        minLength: 6
        type: string
      username:
        description: 必填
        type: string
    required:
    - email
    - password
    - username
    type: object
  models.Item:
    type: object
host: localhost:8080
info:
  contact: {}
  description: 這是一個用 Go 寫的高併發拍賣網站 API 系統，具備 JWT 防護與資料庫悲觀鎖。
  title: Mercari Clone API
  version: "1.0"
paths:
  /items:
    get:
      consumes:
      - application/json
      description: 支援 limit, offset 分頁與 search 關鍵字搜尋
      parameters:
      - description: 限制回傳筆數 (預設 10)
        in: query
        name: limit
        type: integer
      - description: 跳過幾筆資料 (預設 0)
        in: query
        name: offset
        type: integer
      - description: '關鍵字搜尋 (例如: PS5)'
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 取得商品列表
      tags:
      - items
    post:
      consumes:
      - application/json
      description: 建立一個新的商品並存入資料庫，會自動綁定發送請求的賣家身分
      parameters:
      - description: 商品資料 (填寫 name 和 price 即可)
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/models.Item'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Item'
      security:
      - BearerAuth: []
      summary: 新增拍賣商品
      tags:
      - items
  /login:
    post:
      consumes:
      - application/json
      description: 輸入註冊過的帳號密碼來換取 JWT Token
      parameters:
      - description: 請輸入帳號與密碼
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 登入系統取得手環
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: 建立一組新的帳號密碼，密碼將會被 bcrypt 演算法單向加密
      parameters:
      - description: 註冊資料 (需包含 email 與至少 6 碼的密碼)
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 註冊新帳號
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
